### PR TITLE
Added the access log option to the load balancer. 

### PR DESCRIPTION
**Pull request by glennbech**
* Added access logs option 
* Fixed bug in the example ."type" for aws_lb was set  "alb", valid values are "network" and "application"
* Expanded the example to provision two load balancers, on with- and one without Access logs enabled

### CODE REVIEW

**Review by itsdalmo — COMMENTED** [review]
Have you checked whether it's possible to have a single `aws_lb` resource? Some resources are fine with optional/empty input, and I see that you have a `enabled` flag that you might just switch between `true`/`false` if the `access_logs_bucket == ""`?

**Review by larstobi — APPROVED** [review]
LGTM

**Comment by glennbech** [comment]
The resource does not like it. It complains that the value for access_logs_bucket is empty, even if the enabled value is false.

**Comment by glennbech** [comment]
@larstobi @itsdalmo the outputs become problematic right? One output from this module is declared as `

```
output "zone_id" {
  description = "The canonical hosted zone ID of the load balancer (to be used in a Route 53 Alias record)."
  value       = "${aws_lb.main.zone_id}"
}
``` 
But in some instances the aws_lb.main reference is not valid, because the load balancer *with* access logs is created instead. We can't have conditional outputs - so.... a bit confused here .

**Comment by itsdalmo** [comment]
@glennbech - This is what you use `${coalesce(join())}` for I think. Can't remember where I used it last, but here is an example: https://github.com/hashicorp/terraform/issues/12799#issuecomment-291938275

The "best practice" might have changed since 2017, but it _is_ possible to get the output working. Just look at other open source modules and I'm sure you can find an example 👍

**Comment by glennbech** [comment]
@itsdalmo - It works with coalesce( join()) - element(concat(),0) also works and is also quite readable. Not sure what I prefer, but ended up with the coalesce option.

**Review by itsdalmo — APPROVED** [review]
LGTM 💯 - Remember to use the dropdown and "squash and merge" when merging this 😅

**Pull request merged**
